config/routes.rb
Rails.application.routes.draw do
  mount API::V1::Root => '/api/v1'
  mount Refine::Reconcile => '/refine/reconcile'
  mount GrapeSwaggerRails::Engine => '/docs/api/v1'

  devise_for :users

  # Routes that explicitly ask for authentication.
  # These routes prevent visitor routes from using the same URL.
  authenticate :user do
    resources :documents, only: [:index]

    resources :document_exports, except: [:edit, :update] do
      get :download, on: :member
    end

    resources :document_imports, except: [:edit, :update] do
      post :publish, on: :member
    end

    resources :repositories
  end

  # Routes that are unavailable for visitors.
  # These routes allow visitor routes using the same URL.
  authenticated :user do
    root 'welcome#index'
  end

  # Public (visitor) routes.
  root 'visitor/welcome#index', as: :visitor_root

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  after_commit :create_search_index!, on: :create
  after_commit :delete_index,         on: :destroy

  belongs_to :organization

  has_many :document_exports, dependent: :destroy,    autosave: true
  has_many :document_imports, dependent: :destroy,    autosave: true
  has_many :documents,        dependent: :destroy,    autosave: true
  has_many :value_mappings,   dependent: :delete_all, autosave: true

  def self.where_name(name)
    where('name ilike ?', "%#{name}%")
  end

  def search_index
    @search_index ||= Search::Indices::DocumentsIndex.new(repository: self)
  end

  def create_search_index!
    search_index.create_index!
    search_index
  end

  def document_count
    documents.count
  end

  def delete_index
    search_index.delete_index!
  end

  def index_all_documents(skip_indexed: true)
    set = skip_indexed ? documents.where(indexed_at: nil) : documents
    set.find_in_batches { |docs| search_index.bulk_index(docs) }
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < AuthenticatedController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  def index
    @repositories = Repository.all
  end

  def show
  end

  def new
    @repository = Repository.new
  end

  def edit
  end

  def create
    @repository = Repository.new(repository_params)
    @repository.organization = current_organization

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_repository
      @repository = Repository.find(params[:id])
    end

    def repository_params
      params.require(:repository).permit(:name, :public)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= simple_form_for(@repository) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :public %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repositories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= repository.public %></td>
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Public:</strong>
  <%= @repository.public %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>