config/routes.rb
Rails.application.routes.draw do
  mount API::V1::Root => '/api/v1'
  mount Refine::Reconcile => '/refine/reconcile'
  mount GrapeSwaggerRails::Engine => '/docs/api/v1'

  devise_for :users

  # Routes that explicitly ask for authentication.
  # These routes prevent visitor routes from using the same URL.
  authenticate :user do
    resources :documents, only: [:index]

    resources :document_exports, except: [:edit, :update] do
      get :download, on: :member
    end

    resources :document_imports, except: [:edit, :update] do
      post :publish, on: :member
    end

    resources :repositories
  end

  # Routes that are unavailable for visitors.
  # These routes allow visitor routes using the same URL.
  authenticated :user do
    root 'welcome#index'
  end

  # Public (visitor) routes.
  root 'visitor/welcome#index', as: :visitor_root

end

app/models/document_import.rb
require 'csv'

class DocumentImport < ActiveRecord::Base
  HEADER = %w[
    url title description grades publishers
    languages resource_types standards subjects
  ]

  mount_uploader :file, DocumentImportUploader

  belongs_to :repository

  has_many :document_import_rows, dependent: :delete_all
  alias_attribute :rows, :document_import_rows

  validates :file, presence: true
  validates :repository, presence: true
  validate  :check_csv

  def check_csv
    return unless file.try(:url)

    File.open(file.path) do |f|
      begin
        file_header = CSV.parse(f.readline).first.to_a
        unless check_header(file_header)
          errors.add(:file, :headers, headers: HEADER)
        end
      rescue ArgumentError
        errors.add(:file, :not_csv)
      rescue CSV::MalformedCSVError
        errors.add(:file, :malformed_csv)
      end
    end
  end

  def check_header(header)
    HEADER.all? { |h| header.include?(h) }
  end

  # Preparing

  def can_prepare?
    prepared_at.blank?
  end

  #
  # Processes the CSV and extracts valid and invalid documents before the import
  # job is confirmed by the user.
  #
  # Each row in the CSV becomes a row in the document_import_rows table.
  # 
  def prepare_import
    CSV.foreach(file.path, headers: true) do |csv_row|
      row = rows.build
      row.parse_csv_content(csv_row)
      row.save
    end

    touch(:prepared_at)
  end

  # Mapping

  def can_map?
    prepared_at.present? && mapped_at.blank?
  end

  #
  # Creates mappings between row fields and entities in the database.
  # Those mappings will be used when the row is converted to a Document.
  #
  def create_mappings
    rows.find_each do |row|
      row.map_content
      row.save
    end

    touch(:mapped_at)
  end

  # Importing

  def can_import?
    mapped_at.present? && imported_at.blank?
  end

  #
  # Imports rows extracted from a CSV. Each valid row in the document_import_rows
  # table is converted into a full-blown Document.
  # 
  def import
    rows.find_each do |row|
      doc = row.to_document
      doc.skip_indexing = true
      if !doc.save
        row.import_errors ||= {}
        row.import_errors[:document_errors] = doc.errors
        row.save
      end
    end

    touch(:imported_at)
  end

  def import_status
    if imported_at.present?
      :imported
    elsif mapped_at.present?
      :mapped
    elsif prepared_at.present?
      :prepared
    else
      :waiting
    end
  end

  #
  # Goes through the whole process: prepare, mappings and import.
  #
  def process
    prepare_import
    create_mappings
    import
  end
end

app/controllers/document_imports_controller.rb
class DocumentImportsController < AuthenticatedController
  before_action :set_document_import, only: [:show, :destroy, :publish]

  def index
    @document_imports = DocumentImport.all
  end

  def show
    @rows = @document_import.rows.order(id: :asc).page(params[:page] || 1)
  end

  def new
    @document_import = DocumentImport.new
  end

  def create
    @document_import = DocumentImport.new(document_import_params)

    respond_to do |format|
      if @document_import.save
        DocumentImportPrepareWorker.perform_async(@document_import.id)
        format.html { redirect_to @document_import, notice: 'Csv document import was successfully created.' }
        format.json { render :show, status: :created, location: @document_import }
      else
        format.html { render :new }
        format.json { render json: @document_import.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document_import.destroy
    respond_to do |format|
      format.html { redirect_to document_imports_url, notice: 'Csv document import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    if @document_import.can_import?
      DocumentImportWorker.perform_async(@document_import.id)
      respond_to do |format|
        format.html { redirect_to @document_import, notice: 'Csv document import is being imported.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @document_import, notice: 'Csv document import can not be imported yet.' }
        format.json { render json: @document_import.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_document_import
      @document_import = DocumentImport.find(params[:id])
    end

    def document_import_params
      params.require(:document_import).permit(:file, :repository_id)
    end
end

app/helpers/document_imports_helper.rb
module DocumentImportsHelper
end

app/views/document_imports/_form.html.erb
<%= simple_form_for(@document_import) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :repository %>
    <%= f.input :file, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.submit t('ui.upload') %>
  </div>
<% end %>

app/views/document_imports/edit.html.erb
<h1>Editing Csv Document Import</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_import %> |
<%= link_to 'Back', document_imports_path %>

app/views/document_imports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Csv Document Imports</h1>

<table>
  <thead>
    <tr>
      <th><%= t('ui.file') %></th>
      <th><%= t('ui.repository') %></th>
      <th><%= t('ui.status') %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_imports.each do |document_import| %>
      <tr>
        <td><%= document_import.file %></td>
        <td><%= document_import.repository.name %></td>
        <td><%= t("ui.document_import_status.#{document_import.import_status}") %></td>
        <td><%= link_to 'Show', document_import %></td>
        <td><%= link_to 'Destroy', document_import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv document import', new_document_import_path %>

app/views/document_imports/new.html.erb
<h1>New Csv Document Import</h1>

<%= render 'form' %>

<%= link_to 'Back', document_imports_path %>

app/views/document_imports/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Csv Document Import Rows</h1>

<table>
  <thead>
    <tr>
      <th>url</th>
      <th>title</th>
      <th>description</th>
    </tr>
  </thead>

  <tbody>
    <% @rows.each do |document_import_row| %>
      <tr>
        <td><%= document_import_row.content['url'] %></td>
        <td><%= document_import_row.content['title'] %></td>
        <td><%= document_import_row.content['description'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @rows %>

<%= link_to t('ui.publish'), publish_document_import_path(@document_import), method: :post, data: { confirm: 'Are you sure?' } %>