config/routes.rb
Rails.application.routes.draw do
  mount API::V1::Root => '/api/v1'
  mount Refine::Reconcile => '/refine/reconcile'
  mount GrapeSwaggerRails::Engine => '/docs/api/v1'

  devise_for :users

  # Routes that explicitly ask for authentication.
  # These routes prevent visitor routes from using the same URL.
  authenticate :user do
    resources :documents, only: [:index]

    resources :document_exports, except: [:edit, :update] do
      get :download, on: :member
    end

    resources :document_imports, except: [:edit, :update] do
      post :publish, on: :member
    end

    resources :repositories
  end

  # Routes that are unavailable for visitors.
  # These routes allow visitor routes using the same URL.
  authenticated :user do
    root 'welcome#index'
  end

  # Public (visitor) routes.
  root 'visitor/welcome#index', as: :visitor_root

end

app/models/document_export.rb
require 'csv'

class DocumentExport < ActiveRecord::Base
  EXPORT_TYPES = %w[csv]

  belongs_to :repository

  validates :repository, presence: true
  validates :export_type, presence: true, inclusion: EXPORT_TYPES

  def export
    documents = repository.documents

    if filtered_ids.present? && filtered_ids.any?
      documents.where!(id: filtered_ids)
    end

    open_csv do |csv|
      documents.order(id: :desc).find_each do |doc|
        csv << [
          doc.url.url,
          doc.title,
          doc.description,
          doc.grades.pluck(:name).join(','),
          doc.publishers.pluck(:name).join(','),
          doc.languages.pluck(:name).join(','),
          doc.resource_types.pluck(:name).join(',') ,
          doc.standards.pluck(:name).join(',') ,
          doc.subjects.pluck(:name).join(',')
        ]
      end
    end

    self.exported_at = Time.now
    save
  end

  def exported?
    exported_at.present?
  end

  protected

  def open_csv(&blk)
    current_time = "#{Time.now.utc.to_s.gsub(/ /, '_').gsub(/\:/, '-')}"
    path         = Rails.public_path.join('exports', 'csv')
    filename     = "Export_#{repository.id}__#{current_time}.csv"
    file         = path.join(filename).to_s
    headers      = DocumentImport::HEADER

    self.file = file
    FileUtils.mkdir_p(path)
    CSV.open(file, 'wb', write_headers: true, headers: headers, &blk)
  end
end

app/controllers/document_exports_controller.rb
class DocumentExportsController < AuthenticatedController
  before_action :set_document_export, only: [:show, :destroy, :download]

  CONTENT_TYPES = {
    'csv' => 'text/csv'
  }  

  def index
    @document_exports = DocumentExport.all
  end

  def show
  end

  def new
    @document_export = DocumentExport.new
  end

  def create
    @document_export = DocumentExport.new(document_export_params)

    respond_to do |format|
      if @document_export.save
        DocumentExportWorker.perform_async(@document_export.id)
        format.html { redirect_to @document_export, notice: 'Document export was successfully created.' }
        format.json { render :show, status: :created, location: @document_export }
      else
        format.html { render :new }
        format.json { render json: @document_export.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document_export.destroy
    respond_to do |format|
      format.html { redirect_to document_exports_url, notice: 'Document export was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    if @document_export.exported?
      send_file(@document_export.file,
        type: CONTENT_TYPES[@document_export.export_type],
        disposition: :attachment
      )
    end
  end

  private
    def set_document_export
      @document_export = DocumentExport.find(params[:id])
    end

    def document_export_params
      params
        .require(:document_export)
        .permit(:repository_id, :export_type, :filtered_ids)
    end
end

app/helpers/document_exports_helper.rb
module DocumentExportsHelper
end

app/views/document_exports/_form.html.erb
<%= simple_form_for(@document_export) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :repository %>
    <%= f.input :export_type, collection: DocumentExport::EXPORT_TYPES %>
  </div>

  <div class="form-actions">
    <%= f.submit t('ui.export') %>
  </div>
<% end %>

app/views/document_exports/edit.html.erb
<h1>Editing Document Export</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_export %> |
<%= link_to 'Back', document_exports_path %>

app/views/document_exports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Document Exports</h1>

<table>
  <thead>
    <tr>
      <th>Export jid</th>
      <th>Exported at</th>
      <th>Repository</th>
      <th>File</th>
      <th>Export type</th>
      <th>Filtered ids</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_exports.each do |document_export| %>
      <tr>
        <td><%= document_export.export_jid %></td>
        <td><%= document_export.exported_at %></td>
        <td><%= document_export.repository %></td>
        <td><%= document_export.file %></td>
        <td><%= document_export.export_type %></td>
        <td><%= document_export.filtered_ids %></td>
        <td><%= link_to 'Show', document_export %></td>
        <td><%= link_to 'Destroy', document_export, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Download', download_document_export_path(document_export) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document export', new_document_export_path %>

app/views/document_exports/new.html.erb
<h1>New Document Export</h1>

<%= render 'form' %>

<%= link_to 'Back', document_exports_path %>

app/views/document_exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Export jid:</strong>
  <%= @document_export.export_jid %>
</p>

<p>
  <strong>Exported at:</strong>
  <%= @document_export.exported_at %>
</p>

<p>
  <strong>Repository:</strong>
  <%= @document_export.repository %>
</p>

<p>
  <strong>File:</strong>
  <%= @document_export.file %>
</p>

<p>
  <strong>Export type:</strong>
  <%= @document_export.export_type %>
</p>

<p>
  <strong>Filtered ids:</strong>
  <%= @document_export.filtered_ids %>
</p>

<%= link_to 'Back', document_exports_path %>