config/routes.rb
Rails.application.routes.draw do
  mount API::V1::Root => '/api/v1'
  mount Refine::Reconcile => '/refine/reconcile'
  mount GrapeSwaggerRails::Engine => '/docs/api/v1'

  devise_for :users

  # Routes that explicitly ask for authentication.
  # These routes prevent visitor routes from using the same URL.
  authenticate :user do
    resources :documents, only: [:index]

    resources :document_exports, except: [:edit, :update] do
      get :download, on: :member
    end

    resources :document_imports, except: [:edit, :update] do
      post :publish, on: :member
    end

    resources :repositories
  end

  # Routes that are unavailable for visitors.
  # These routes allow visitor routes using the same URL.
  authenticated :user do
    root 'welcome#index'
  end

  # Public (visitor) routes.
  root 'visitor/welcome#index', as: :visitor_root

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :document_status
  belongs_to :repository
  belongs_to :url

  has_many :document_grades,         dependent: :delete_all, autosave: true
  has_many :document_identities,     dependent: :delete_all, autosave: true
  has_many :document_languages,      dependent: :delete_all, autosave: true
  has_many :document_resource_types, dependent: :delete_all, autosave: true
  has_many :document_standards,      dependent: :delete_all, autosave: true
  has_many :document_subjects,       dependent: :delete_all, autosave: true

  has_many :identities,     through: :document_identities
  has_many :grades,         through: :document_grades
  has_many :languages,      through: :document_languages
  has_many :resource_types, through: :document_resource_types
  has_many :standards,      through: :document_standards
  has_many :subjects,       through: :document_subjects

  validates :url,   presence: true
  validates :title, presence: true

  include Indexable
  acts_as_indexed

  def self.find_by_url(url)
    where(url: Url.find_by(url: url)).first
  end

  #
  # Adds an identity of a certain type
  #
  def add_identity(identity, idt_type_val)
    document_identities.build(
      identity: identity,
      identity_type: IdentityType.find_by(value: idt_type_val)
    )
  end

  #
  # Finds identities by identity type.
  #
  def identities_of(idt_type_val)
    Identity
      .joins(:document_identities)
      .where('document_identities.document_id = ?', self.id)
      .where('document_identities.identity_type_id = ?',
        IdentityType.find_by(value: idt_type_val).id)
  end

  #
  # Returns publisher identities
  #
  def publishers
    identities_of(:publisher)
  end

  # This is just a handy method to get the correct timezone for doing
  # manual .touch operations in bulk.
  def _current_time_from_proper_timezone
    current_time_from_proper_timezone
  end

end

app/controllers/documents_controller.rb
class DocumentsController < AuthenticatedController
  def index
    @documents = Document.order(id: :asc).page(params[:page] || 1)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Grades</th>
      <th>Publishers</th>
      <th>Languages</th>
      <th>Resource Types</th>
      <th>Standards</th>
      <th>Subjects</th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.description %></td>
        <td><%= document.grades.pluck(:name).join(',') %></td>
        <td><%= document.publishers.pluck(:name).join(',') %></td>
        <td><%= document.languages.pluck(:name).join(',') %></td>
        <td><%= document.resource_types.pluck(:name).join(',') %></td>
        <td><%= document.standards.pluck(:name).join(',') %></td>
        <td><%= document.subjects.pluck(:name).join(',') %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= paginate @documents %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>